CREATE TABLE `job_description_assets` (
  `id` VARCHAR(191) NOT NULL,
  `company_id` VARCHAR(191) NOT NULL,
  `job_id` VARCHAR(191) NOT NULL,
  `source_type` ENUM('PASTED_TEXT', 'PDF_UPLOAD', 'DOCX_UPLOAD') NOT NULL,
  `status` ENUM('TEXT_EXTRACTED', 'EXTRACTION_FAILED') NOT NULL DEFAULT 'TEXT_EXTRACTED',
  `file_name` VARCHAR(191) NULL,
  `mime_type` VARCHAR(191) NULL,
  `storage_key` VARCHAR(191) NULL,
  `extracted_text` LONGTEXT NOT NULL,
  `text_hash` VARCHAR(191) NOT NULL,
  `metadata_json` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `job_description_assets_company_id_id_key` (`company_id`, `id`),
  INDEX `job_description_assets_company_id_job_id_created_at_idx` (`company_id`, `job_id`, `created_at`),
  INDEX `job_description_assets_company_id_text_hash_idx` (`company_id`, `text_hash`),
  CONSTRAINT `job_description_assets_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `job_description_assets_company_id_job_id_fkey` FOREIGN KEY (`company_id`, `job_id`) REFERENCES `jobs`(`company_id`, `id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `job_intelligence_profiles` (
  `id` VARCHAR(191) NOT NULL,
  `company_id` VARCHAR(191) NOT NULL,
  `job_id` VARCHAR(191) NOT NULL,
  `source_asset_id` VARCHAR(191) NULL,
  `status` ENUM('DRAFT', 'AI_ANALYSIS_PENDING', 'AI_ANALYSIS_READY', 'HR_REVIEW_NEEDED', 'PUBLISHED', 'CLOSED', 'ARCHIVED') NOT NULL DEFAULT 'DRAFT',
  `title` VARCHAR(191) NOT NULL,
  `department_text` VARCHAR(191) NULL,
  `employment_type_text` VARCHAR(191) NULL,
  `workplace_text` VARCHAR(191) NULL,
  `location_text` VARCHAR(191) NULL,
  `experience_text` VARCHAR(191) NULL,
  `responsibilities_json` JSON NOT NULL,
  `required_skills_json` JSON NOT NULL,
  `nice_to_have_skills_json` JSON NOT NULL,
  `education_json` JSON NOT NULL,
  `tools_json` JSON NOT NULL,
  `seniority_json` JSON NOT NULL,
  `screening_criteria_json` JSON NOT NULL,
  `competencies_json` JSON NOT NULL,
  `interview_structure_json` JSON NOT NULL,
  `rubric_json` JSON NOT NULL,
  `red_flags_json` JSON NOT NULL,
  `raw_ai_json` JSON NULL,
  `failure_message` TEXT NULL,
  `analyzed_at` DATETIME(3) NULL,
  `edited_at` DATETIME(3) NULL,
  `published_at` DATETIME(3) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `job_intelligence_profiles_company_id_id_key` (`company_id`, `id`),
  UNIQUE INDEX `job_intelligence_profiles_company_id_job_id_key` (`company_id`, `job_id`),
  INDEX `job_intelligence_profiles_company_id_source_asset_id_idx` (`company_id`, `source_asset_id`),
  INDEX `job_intelligence_profiles_company_id_status_updated_at_idx` (`company_id`, `status`, `updated_at`),
  CONSTRAINT `job_intelligence_profiles_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `job_intelligence_profiles_company_id_job_id_fkey` FOREIGN KEY (`company_id`, `job_id`) REFERENCES `jobs`(`company_id`, `id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `job_intelligence_profiles_company_id_source_asset_id_fkey` FOREIGN KEY (`company_id`, `source_asset_id`) REFERENCES `job_description_assets`(`company_id`, `id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `job_interview_questions` (
  `id` VARCHAR(191) NOT NULL,
  `company_id` VARCHAR(191) NOT NULL,
  `job_id` VARCHAR(191) NOT NULL,
  `sequence` INTEGER NOT NULL,
  `competency_name` VARCHAR(191) NOT NULL,
  `competency_description` TEXT NULL,
  `question_text` TEXT NOT NULL,
  `question_type` VARCHAR(191) NOT NULL,
  `difficulty` VARCHAR(191) NOT NULL,
  `expected_signals_json` JSON NOT NULL,
  `scoring_rubric_json` JSON NOT NULL,
  `red_flags_json` JSON NOT NULL,
  `follow_ups_json` JSON NOT NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `job_interview_questions_company_id_id_key` (`company_id`, `id`),
  UNIQUE INDEX `job_interview_questions_company_id_job_id_sequence_key` (`company_id`, `job_id`, `sequence`),
  INDEX `job_interview_questions_company_id_job_id_idx` (`company_id`, `job_id`),
  CONSTRAINT `job_interview_questions_company_id_fkey` FOREIGN KEY (`company_id`) REFERENCES `companies`(`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `job_interview_questions_company_id_job_id_fkey` FOREIGN KEY (`company_id`, `job_id`) REFERENCES `jobs`(`company_id`, `id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
