ALTER TABLE `candidate_applications`
  MODIFY `status` ENUM(
    'NEW',
    'IN_REVIEW',
    'SHORTLISTED',
    'NOT_SELECTED',
    'AVAILABILITY_REQUESTED',
    'AVAILABILITY_CONFIRMED',
    'INTERVIEW_INVITED',
    'INTERVIEW_COMPLETED',
    'INTERVIEW',
    'OFFER',
    'HIRED',
    'REJECTED',
    'WITHDRAWN',
    'ARCHIVED'
  ) NOT NULL DEFAULT 'NEW';

CREATE TABLE `application_decision_history` (
  `id` VARCHAR(191) NOT NULL,
  `company_id` VARCHAR(191) NOT NULL,
  `application_id` VARCHAR(191) NOT NULL,
  `candidate_id` VARCHAR(191) NOT NULL,
  `job_id` VARCHAR(191) NOT NULL,
  `decision` ENUM('SHORTLISTED', 'NOT_SELECTED', 'RETURNED_TO_REVIEW') NOT NULL,
  `note` TEXT NULL,
  `created_by_user_id` VARCHAR(191) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  PRIMARY KEY (`id`),
  UNIQUE KEY `adh_company_id_key` (`company_id`, `id`),
  KEY `adh_app_created_idx` (`company_id`, `application_id`, `created_at`),
  KEY `adh_candidate_idx` (`company_id`, `candidate_id`),
  KEY `adh_job_idx` (`company_id`, `job_id`),
  KEY `adh_created_by_idx` (`company_id`, `created_by_user_id`),
  CONSTRAINT `adh_company_fk` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `adh_app_fk` FOREIGN KEY (`company_id`, `application_id`) REFERENCES `candidate_applications` (`company_id`, `id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `adh_candidate_fk` FOREIGN KEY (`company_id`, `candidate_id`) REFERENCES `candidates` (`company_id`, `id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `adh_job_fk` FOREIGN KEY (`company_id`, `job_id`) REFERENCES `jobs` (`company_id`, `id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `adh_user_fk` FOREIGN KEY (`company_id`, `created_by_user_id`) REFERENCES `users` (`company_id`, `id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `interview_availability_slots` (
  `id` VARCHAR(191) NOT NULL,
  `company_id` VARCHAR(191) NOT NULL,
  `job_id` VARCHAR(191) NOT NULL,
  `start_at` DATETIME(3) NOT NULL,
  `end_at` DATETIME(3) NOT NULL,
  `timezone` VARCHAR(191) NOT NULL,
  `location_note` TEXT NULL,
  `is_online` BOOLEAN NOT NULL DEFAULT true,
  `status` ENUM('OPEN', 'SELECTED', 'EXPIRED', 'CANCELLED') NOT NULL DEFAULT 'OPEN',
  `selected_application_id` VARCHAR(191) NULL,
  `selected_at` DATETIME(3) NULL,
  `created_by_user_id` VARCHAR(191) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  `cancelled_at` DATETIME(3) NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `ias_company_id_key` (`company_id`, `id`),
  KEY `ias_job_status_start_idx` (`company_id`, `job_id`, `status`, `start_at`),
  KEY `ias_selected_app_idx` (`company_id`, `selected_application_id`),
  KEY `ias_created_by_idx` (`company_id`, `created_by_user_id`),
  CONSTRAINT `ias_company_fk` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ias_job_fk` FOREIGN KEY (`company_id`, `job_id`) REFERENCES `jobs` (`company_id`, `id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `ias_app_fk` FOREIGN KEY (`company_id`, `selected_application_id`) REFERENCES `candidate_applications` (`company_id`, `id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `ias_user_fk` FOREIGN KEY (`company_id`, `created_by_user_id`) REFERENCES `users` (`company_id`, `id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

CREATE TABLE `application_availability_requests` (
  `id` VARCHAR(191) NOT NULL,
  `company_id` VARCHAR(191) NOT NULL,
  `job_id` VARCHAR(191) NOT NULL,
  `application_id` VARCHAR(191) NOT NULL,
  `candidate_id` VARCHAR(191) NOT NULL,
  `candidate_account_id` VARCHAR(191) NULL,
  `token_hash` VARCHAR(191) NOT NULL,
  `token_salt` VARCHAR(191) NOT NULL,
  `status` ENUM('ACTIVE', 'CONFIRMED', 'EXPIRED', 'CANCELLED') NOT NULL DEFAULT 'ACTIVE',
  `expires_at` DATETIME(3) NOT NULL,
  `sent_at` DATETIME(3) NULL,
  `confirmed_at` DATETIME(3) NULL,
  `cancelled_at` DATETIME(3) NULL,
  `selected_slot_id` VARCHAR(191) NULL,
  `email_status` VARCHAR(191) NOT NULL DEFAULT 'LINK_GENERATED',
  `created_by_user_id` VARCHAR(191) NULL,
  `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updated_at` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `aar_token_hash_key` (`token_hash`),
  UNIQUE KEY `aar_company_id_key` (`company_id`, `id`),
  KEY `aar_app_status_idx` (`company_id`, `application_id`, `status`),
  KEY `aar_job_status_exp_idx` (`company_id`, `job_id`, `status`, `expires_at`),
  KEY `aar_cand_acc_idx` (`company_id`, `candidate_account_id`),
  KEY `aar_selected_slot_idx` (`company_id`, `selected_slot_id`),
  KEY `aar_created_by_idx` (`company_id`, `created_by_user_id`),
  CONSTRAINT `aar_company_fk` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `aar_job_fk` FOREIGN KEY (`company_id`, `job_id`) REFERENCES `jobs` (`company_id`, `id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `aar_app_fk` FOREIGN KEY (`company_id`, `application_id`) REFERENCES `candidate_applications` (`company_id`, `id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `aar_candidate_fk` FOREIGN KEY (`company_id`, `candidate_id`) REFERENCES `candidates` (`company_id`, `id`) ON DELETE CASCADE ON UPDATE CASCADE,
  CONSTRAINT `aar_cand_acc_fk` FOREIGN KEY (`company_id`, `candidate_account_id`) REFERENCES `candidate_accounts` (`company_id`, `id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `aar_slot_fk` FOREIGN KEY (`company_id`, `selected_slot_id`) REFERENCES `interview_availability_slots` (`company_id`, `id`) ON DELETE RESTRICT ON UPDATE CASCADE,
  CONSTRAINT `aar_user_fk` FOREIGN KEY (`company_id`, `created_by_user_id`) REFERENCES `users` (`company_id`, `id`) ON DELETE RESTRICT ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
