ALTER TABLE `notification_intents`
  MODIFY COLUMN `type` ENUM(
    'INVITATION_CREATED',
    'INVITATION_REMINDER',
    'SCHEDULE_CREATED',
    'SCHEDULE_UPDATED',
    'CANDIDATE_ACCOMMODATION_REQUESTED',
    'CANDIDATE_SUPPORT_REQUESTED',
    'CANDIDATE_WITHDRAWN',
    'RESULTS_READY',
    'APPLICATION_DECISION'
  ) NOT NULL;
