ALTER TABLE `notification_intents`
  MODIFY COLUMN `type` ENUM(
    'INVITATION_CREATED',
    'INVITATION_REMINDER',
    'SCHEDULE_CREATED',
    'SCHEDULE_UPDATED',
    'CANDIDATE_ACCOMMODATION_REQUESTED',
    'CANDIDATE_SUPPORT_REQUESTED',
    'CANDIDATE_WITHDRAWN',
    'RESULTS_READY',
    'APPLICATION_DECISION'
  ) NOT NULL;

ALTER TABLE `email_templates`
  MODIFY COLUMN `key` ENUM(
    'INTERVIEW_INVITATION',
    'INTERVIEW_REMINDER',
    'INVITATION_EXPIRED',
    'EMAIL_VERIFICATION',
    'PASSWORD_RESET',
    'APPLICATION_DECISION'
  ) NOT NULL;

ALTER TABLE `email_deliveries`
  MODIFY COLUMN `template_key` ENUM(
    'INTERVIEW_INVITATION',
    'INTERVIEW_REMINDER',
    'INVITATION_EXPIRED',
    'EMAIL_VERIFICATION',
    'PASSWORD_RESET',
    'APPLICATION_DECISION'
  ) NOT NULL;
